"use client";

import { useEffect, useState, Suspense } from "react";
import { useSearchParams } from "next/navigation";
import { jsPDF } from "jspdf";
import { Loader2, Download, CheckCircle2, AlertCircle } from "lucide-react";
import Link from "next/link";

function DownloadLogic() {
  const searchParams = useSearchParams();
  const [status, setStatus] = useState<"loading" | "success" | "error">("loading");

  useEffect(() => {
    const dataParam = searchParams.get("data");
    if (!dataParam) {
      setStatus("error");
      return;
    }

    try {
      // Decode Base64 Payload
      const jsonString = atob(dataParam);
      const profileInfo = JSON.parse(jsonString);

      generatePDF(profileInfo);
      setStatus("success");
    } catch (e) {
      console.error("Failed to parse profile data for PDF:", e);
      setStatus("error");
    }
  }, [searchParams]);

  const generatePDF = (data: any) => {
    const doc = new jsPDF();
    
    // Header
    doc.setFillColor(14, 148, 136); // Teal-600
    doc.rect(0, 0, 210, 40, "F");
    
    doc.setTextColor(255, 255, 255);
    doc.setFont("helvetica", "bold");
    doc.setFontSize(24);
    doc.text("SWASTHYA DIGITAL HEALTH CARD", 105, 20, { align: "center" });
    
    doc.setFontSize(12);
    doc.setFont("helvetica", "normal");
    doc.text(`Generated on: ${new Date().toLocaleDateString()}`, 105, 30, { align: "center" });

    // Rest of document text color
    doc.setTextColor(50, 50, 50);

    // Section: Personal Details
    doc.setFontSize(16);
    doc.setFont("helvetica", "bold");
    doc.text("Personal Information", 20, 55);
    doc.setDrawColor(200, 200, 200);
    doc.line(20, 58, 190, 58);

    doc.setFontSize(12);
    doc.setFont("helvetica", "bold");
    doc.text("Full Name:", 20, 70);
    doc.setFont("helvetica", "normal");
    doc.text(data.name || "N/A", 60, 70);

    doc.setFont("helvetica", "bold");
    doc.text("Age:", 20, 80);
    doc.setFont("helvetica", "normal");
    doc.text(String(data.age || "N/A"), 60, 80);

    doc.setFont("helvetica", "bold");
    doc.text("Gender:", 110, 80);
    doc.setFont("helvetica", "normal");
    doc.text(data.gender || "N/A", 140, 80);

    doc.setFont("helvetica", "bold");
    doc.text("Phone No:", 20, 90);
    doc.setFont("helvetica", "normal");
    doc.text(data.phone || "N/A", 60, 90);

    doc.setFont("helvetica", "bold");
    doc.text("Email ID:", 110, 90);
    doc.setFont("helvetica", "normal");
    doc.text(data.email || "N/A", 140, 90);

    // Section: Medical Details
    doc.setFontSize(16);
    doc.setFont("helvetica", "bold");
    doc.text("Basic Health Details", 20, 115);
    doc.line(20, 118, 190, 118);

    doc.setFontSize(12);
    
    // Blood Type
    doc.setFillColor(255, 241, 242); // Rose-50
    doc.rect(20, 125, 80, 25, "F");
    doc.setFont("helvetica", "bold");
    doc.setTextColor(225, 29, 72); // Rose-600
    doc.text("Blood Type", 25, 135);
    doc.setFont("helvetica", "normal");
    doc.setTextColor(50, 50, 50);
    doc.text(data.bloodType || "N/A", 25, 145);

    // BMI
    doc.setFillColor(236, 253, 245); // Emerald-50
    doc.rect(110, 125, 80, 25, "F");
    doc.setFont("helvetica", "bold");
    doc.setTextColor(5, 150, 105); // Emerald-600
    doc.text("BMI Index", 115, 135);
    doc.setFont("helvetica", "normal");
    doc.setTextColor(50, 50, 50);
    doc.text(String(data.bmi || "N/A"), 115, 145);

    // Allergies
    doc.setFillColor(255, 251, 235); // Amber-50
    doc.rect(20, 155, 80, 25, "F");
    doc.setFont("helvetica", "bold");
    doc.setTextColor(217, 119, 6); // Amber-600
    doc.text("Known Allergies", 25, 165);
    doc.setFont("helvetica", "normal");
    doc.setTextColor(50, 50, 50);
    const allergiesStr = Array.isArray(data.allergies) ? data.allergies.join(", ") : data.allergies || "None";
    doc.text(allergiesStr, 25, 175);

    // Disabilities
    doc.setFillColor(239, 246, 255); // Blue-50
    doc.rect(110, 155, 80, 25, "F");
    doc.setFont("helvetica", "bold");
    doc.setTextColor(37, 99, 235); // Blue-600
    doc.text("Disabilities", 115, 165);
    doc.setFont("helvetica", "normal");
    doc.setTextColor(50, 50, 50);
    doc.text(data.disabilities || "None", 115, 175);

    // Footer
    doc.setFontSize(10);
    doc.setTextColor(150, 150, 150);
    doc.text("This document is auto-generated by your Swasthya profile scan.", 105, 280, { align: "center" });

    // Download
    setTimeout(() => {
       doc.save(`Swasthya_Profile_${data.name ? data.name.replace(/\s+/g, '_') : 'Scan'}.pdf`);
    }, 500);
  };

  return (
    <div className="flex flex-col items-center justify-center min-h-[60vh] text-center px-4">
      {status === "loading" && (
        <>
          <Loader2 className="w-16 h-16 text-teal-500 animate-spin mb-6" />
          <h2 className="text-2xl font-black text-slate-800 tracking-tight">Generating Profile PDF...</h2>
          <p className="text-slate-500 font-medium mt-2">Please wait while we assemble your digital health card.</p>
        </>
      )}

      {status === "success" && (
        <>
          <div className="w-20 h-20 bg-emerald-100 text-emerald-600 rounded-full flex items-center justify-center mb-6 shadow-sm border border-emerald-200">
             <CheckCircle2 size={40} className="animate-in zoom-in" strokeWidth={2.5} />
          </div>
          <h2 className="text-2xl sm:text-3xl font-black text-slate-800 tracking-tight mb-3">Download Successful!</h2>
          <p className="text-slate-500 font-medium mb-8 max-w-sm">Your medical profile has been successfully saved as a PDF document on your device.</p>
          
          <Link href="/home" className="bg-slate-900 text-white font-bold px-8 py-3.5 rounded-xl shadow-lg hover:bg-slate-800 transition-colors">
             Return to Swasthya
          </Link>
        </>
      )}

      {status === "error" && (
        <>
          <div className="w-20 h-20 bg-rose-100 text-rose-600 rounded-full flex items-center justify-center mb-6 shadow-sm border border-rose-200">
             <AlertCircle size={40} strokeWidth={2.5} />
          </div>
          <h2 className="text-2xl font-black text-slate-800 tracking-tight mb-2">Invalid QR Code</h2>
          <p className="text-slate-500 font-medium mb-8">The scanned QR code does not contain valid Swasthya profile data.</p>
          
          <Link href="/home" className="bg-slate-100 text-slate-700 font-bold px-8 py-3.5 rounded-xl hover:bg-slate-200 transition-colors">
             Go to Homepage
          </Link>
        </>
      )}
    </div>
  );
}

export default function DownloadPDFRoute() {
  return (
    <div className="min-h-screen bg-white">
       {/* Simple Header */}
       <header className="px-6 py-5 border-b border-slate-100 flex items-center justify-between">
         <div className="flex items-center gap-3">
           <img src="/logo.svg" alt="Swasthya" className="w-8 h-8" />
           <span className="text-xl font-black text-slate-800 tracking-tight">Swasthya Download System</span>
         </div>
       </header>

       <Suspense fallback={<div className="p-20 text-center text-slate-400">Loading download system...</div>}>
         <DownloadLogic />
       </Suspense>
    </div>
  );
}
